export type SidebarProps = {
  onAddRect: () => void;
  onAddCircle: () => void;
  onAddTriangle: () => void;
  selected: boolean;
  fillColor: string;
  strokeColor: string;
  strokeWidth: number;
  widthVal: number;
  heightVal: number;
  zIndex: number;
  setFillColor: (v: string) => void;
  setStrokeColor: (v: string) => void;
  setStrokeWidth: (v: number) => void;
  setWidthVal: (v: number) => void;
  setHeightVal: (v: number) => void;
  setZIndex: (v: number) => void;
  borderStyle: string;
  setBorderStyle: (v: string) => void;
  onBringForward: () => void;
  onSendBackward: () => void;
  onApply: () => void;
};
